dataset_path: data
seed: 42
num_epoch: 100
sequence_length: 2  # 修正: sequence_lengthを追加
data_loader:
  common:
    num_voxel_bins: 15
  train:
    batch_size: 16
    shuffle: True
  test:
    batch_size: 1
    shuffle: false
train:
  no_batch_norm: false
  initial_learning_rate: 0.0005
  weight_decay: 0.001
  epochs: 10
  